# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisUi(object):
    def setupUi(self, jarvisUi):
        jarvisUi.setObjectName("jarvisUi")
        jarvisUi.resize(1925, 1058)
        self.centralwidget = QtWidgets.QWidget(jarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-6, 5, 1931, 1031))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../Gui/B.G/Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(20, 20, 671, 481))
        self.bg_2.setStyleSheet("background-color: rgb(5, 209, 255);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(760, 20, 661, 481))
        self.bg_3.setStyleSheet("background-color: rgb(5, 209, 255);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(30, 30, 651, 461))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("../Gui/ExtraGui/fiugi.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(770, 30, 641, 461))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("../Gui/ExtraGui/live.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(-140, 500, 721, 501))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("../Gui/VoiceReg/Aqua.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(1560, 40, 321, 271))
        self.bg_4.setStyleSheet("background-color: rgb(5, 209, 255);")
        self.bg_4.setText("")
        self.bg_4.setPixmap(QtGui.QPixmap("../Gui/ExtraGui/Earth.gif"))
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(1540, 350, 341, 171))
        self.bg_5.setStyleSheet("background-color: rgb(5, 209, 255);")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(1570, 370, 281, 61))
        self.pushButton_Start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 24pt \"Courier New\";\n"
"color: rgb(85, 255, 255);font: 21pt \"Courier New\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(85, 255, 255);\n"
"border-radius:none")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(1570, 440, 281, 61))
        self.pushButton_Exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 24pt \"Courier New\";\n"
"color: rgb(85, 255, 255);font: 21pt \"Courier New\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(85, 255, 255);\n"
"border-radius:none")
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, 540, 671, 441))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(480, 610, 891, 341))
        self.bg_6.setStyleSheet("background-color: rgb(5, 209, 255);")
        self.bg_6.setText("")
        self.bg_6.setObjectName("bg_6")
        self.Youtube = QtWidgets.QPushButton(self.centralwidget)
        self.Youtube.setGeometry(QtCore.QRect(880, 530, 131, 51))
        self.Youtube.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 90 20pt \"Calibri\";")
        self.Youtube.setObjectName("Youtube")
        self.Chrome = QtWidgets.QPushButton(self.centralwidget)
        self.Chrome.setGeometry(QtCore.QRect(1050, 530, 131, 51))
        self.Chrome.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 90 20pt \"Calibri\";")
        self.Chrome.setObjectName("Chrome")
        self.Whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.Whatsapp.setGeometry(QtCore.QRect(1220, 530, 131, 51))
        self.Whatsapp.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 90 18pt \"Calibri\";")
        self.Whatsapp.setObjectName("Whatsapp")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 620, 871, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Gui/ExtraGui/Health_Template.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1440, 610, 451, 321))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Gui/ExtraGui/gga.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        jarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvisUi)
        QtCore.QMetaObject.connectSlotsByName(jarvisUi)

    def retranslateUi(self, jarvisUi):
        _translate = QtCore.QCoreApplication.translate
        jarvisUi.setWindowTitle(_translate("jarvisUi", "MainWindow"))
        self.pushButton_Start.setText(_translate("jarvisUi", "START"))
        self.pushButton_Exit.setText(_translate("jarvisUi", "EXIT"))
        self.Youtube.setText(_translate("jarvisUi", "YouTube"))
        self.Chrome.setText(_translate("jarvisUi", "Chrome"))
        self.Whatsapp.setText(_translate("jarvisUi", "WhatsApp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUi = QtWidgets.QMainWindow()
    ui = Ui_jarvisUi()
    ui.setupUi(jarvisUi)
    jarvisUi.show()
    sys.exit(app.exec_())
